// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20231126092820_Rolagem")]
    partial class Rolagem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("BackEnd.Models.DadoComposto", b =>
                {
                    b.Property<int>("DadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DadosCompostos", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoModFixo", b =>
                {
                    b.Property<int>("DadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModificadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoId", "ModificadorId");

                    b.HasIndex("ModificadorId");

                    b.ToTable("DadoCompostoModFixo");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoModVar", b =>
                {
                    b.Property<int>("ConectDadoVarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModificadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConectDadoVarId");

                    b.HasIndex("DadoId");

                    b.HasIndex("ModificadorId");

                    b.ToTable("DadoCompostoModVar");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSala", b =>
                {
                    b.Property<int>("DadoCompostoSalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcessoPrivado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoCompostoSalaId");

                    b.HasIndex("CriadorId");

                    b.HasIndex("SalaId");

                    b.ToTable("DadosCompostosSalas");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSalaModFixo", b =>
                {
                    b.Property<int>("ConectDadoFixoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModificadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConectDadoFixoId");

                    b.HasIndex("DadoId");

                    b.HasIndex("ModificadorId");

                    b.ToTable("DadoCompostoSalaModFixo");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSalaModVar", b =>
                {
                    b.Property<int>("ConectDadoVarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModificadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConectDadoVarId");

                    b.HasIndex("DadoId");

                    b.ToTable("DadoCompostoSalaModVar");
                });

            modelBuilder.Entity("BackEnd.Models.DadoSimples", b =>
                {
                    b.Property<int>("DadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModificadorVariavelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DadosSimples", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.DadoSimplesSala", b =>
                {
                    b.Property<int>("DadoSimplesSalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcessoPrivado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoSimplesSalaId");

                    b.HasIndex("CriadorId");

                    b.HasIndex("SalaId");

                    b.ToTable("DadosSimplesSalas");
                });

            modelBuilder.Entity("BackEnd.Models.ModificadorFixo", b =>
                {
                    b.Property<int>("ModificadorFixoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModificadorFixoId");

                    b.ToTable("ModificadoresFixos");
                });

            modelBuilder.Entity("BackEnd.Models.ModificadorVariavel", b =>
                {
                    b.Property<int>("ModificadorVariavelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoSimplesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ModificadorVariavelId");

                    b.HasIndex("DadoSimplesId")
                        .IsUnique();

                    b.ToTable("ModificadoresVariaveis");
                });

            modelBuilder.Entity("BackEnd.Models.RolagemDadoSala", b =>
                {
                    b.Property<int>("RolagemDadoSalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoCompostoSalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RoladoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoRolagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RolagemDadoSalaId");

                    b.HasIndex("DadoCompostoSalaId");

                    b.HasIndex("SalaId");

                    b.ToTable("RolagensDadosSalas");
                });

            modelBuilder.Entity("BackEnd.Models.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSimples")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioMestreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalaId");

                    b.HasIndex("UsuarioMestreId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("BackEnd.Models.SalaUsuario", b =>
                {
                    b.Property<int>("SalaUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalaUsuarioId");

                    b.HasIndex("SalaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SalaUsuario");
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BackEnd.Models.DadoComposto", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", null)
                        .WithMany("DadosCompostosPessoais")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoModFixo", b =>
                {
                    b.HasOne("BackEnd.Models.DadoComposto", "DadoComposto")
                        .WithMany("Fixos")
                        .HasForeignKey("DadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.ModificadorFixo", "ModificadorFixo")
                        .WithMany("Fixos")
                        .HasForeignKey("ModificadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoComposto");

                    b.Navigation("ModificadorFixo");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoModVar", b =>
                {
                    b.HasOne("BackEnd.Models.DadoComposto", "DadoComposto")
                        .WithMany("Variaveis")
                        .HasForeignKey("DadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.ModificadorVariavel", "ModificadorVariavel")
                        .WithMany("Variaveis")
                        .HasForeignKey("ModificadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoComposto");

                    b.Navigation("ModificadorVariavel");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSala", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Sala", null)
                        .WithMany("DadosCompostosSala")
                        .HasForeignKey("SalaId");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSalaModFixo", b =>
                {
                    b.HasOne("BackEnd.Models.ModificadorFixo", "ModificadorFixo")
                        .WithMany("FixosSala")
                        .HasForeignKey("DadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.DadoCompostoSala", "DadoCompostoSala")
                        .WithMany("Fixos")
                        .HasForeignKey("ModificadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoCompostoSala");

                    b.Navigation("ModificadorFixo");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSalaModVar", b =>
                {
                    b.HasOne("BackEnd.Models.DadoCompostoSala", "DadoCompostoSala")
                        .WithMany("Variaveis")
                        .HasForeignKey("DadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.ModificadorVariavel", "ModificadorVariavel")
                        .WithMany("VariaveisSala")
                        .HasForeignKey("DadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoCompostoSala");

                    b.Navigation("ModificadorVariavel");
                });

            modelBuilder.Entity("BackEnd.Models.DadoSimples", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", null)
                        .WithMany("DadosSimplesPessoais")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("BackEnd.Models.DadoSimplesSala", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Sala", null)
                        .WithMany("DadosSimplesSala")
                        .HasForeignKey("SalaId");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("BackEnd.Models.ModificadorVariavel", b =>
                {
                    b.HasOne("BackEnd.Models.DadoSimples", "Dado")
                        .WithOne("ModificadorVariavel")
                        .HasForeignKey("BackEnd.Models.ModificadorVariavel", "DadoSimplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dado");
                });

            modelBuilder.Entity("BackEnd.Models.RolagemDadoSala", b =>
                {
                    b.HasOne("BackEnd.Models.DadoCompostoSala", "DadoComposto")
                        .WithMany()
                        .HasForeignKey("DadoCompostoSalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoComposto");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("BackEnd.Models.Sala", b =>
                {
                    b.HasOne("BackEnd.Models.Usuario", "UsuarioMestre")
                        .WithMany()
                        .HasForeignKey("UsuarioMestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMestre");
                });

            modelBuilder.Entity("BackEnd.Models.SalaUsuario", b =>
                {
                    b.HasOne("BackEnd.Models.Sala", "Sala")
                        .WithMany("Convidados")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Usuario", "Usuario")
                        .WithMany("Salas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEnd.Models.DadoComposto", b =>
                {
                    b.Navigation("Fixos");

                    b.Navigation("Variaveis");
                });

            modelBuilder.Entity("BackEnd.Models.DadoCompostoSala", b =>
                {
                    b.Navigation("Fixos");

                    b.Navigation("Variaveis");
                });

            modelBuilder.Entity("BackEnd.Models.DadoSimples", b =>
                {
                    b.Navigation("ModificadorVariavel")
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.ModificadorFixo", b =>
                {
                    b.Navigation("Fixos");

                    b.Navigation("FixosSala");
                });

            modelBuilder.Entity("BackEnd.Models.ModificadorVariavel", b =>
                {
                    b.Navigation("Variaveis");

                    b.Navigation("VariaveisSala");
                });

            modelBuilder.Entity("BackEnd.Models.Sala", b =>
                {
                    b.Navigation("Convidados");

                    b.Navigation("DadosCompostosSala");

                    b.Navigation("DadosSimplesSala");
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.Navigation("DadosCompostosPessoais");

                    b.Navigation("DadosSimplesPessoais");

                    b.Navigation("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
