// <auto-generated />
using System;
using Dicenamics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dicenamics.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20231003131250_DadoBasicoTableAndConfig")]
    partial class DadoBasicoTableAndConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("Dicenamics.Models.DadoBasico", b =>
                {
                    b.Property<int>("Faces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Faces");

                    b.ToTable("DadosBasicos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DadoBasico");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorFixo", b =>
                {
                    b.Property<int>("ModificadorFixoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModificadorFixoId");

                    b.ToTable("ModificadoresFixos");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorVariavel", b =>
                {
                    b.Property<int>("ModificadorVariavelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DadoFaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ModificadorVariavelId");

                    b.HasIndex("DadoFaces");

                    b.ToTable("ModificadoresVariaveis");
                });

            modelBuilder.Entity("Dicenamics.Models.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSimples")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioMestreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalaId");

                    b.HasIndex("UsuarioMestreId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Dicenamics.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId");

                    b.HasIndex("SalaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoSimples", b =>
                {
                    b.HasBaseType("Dicenamics.Models.DadoBasico");

                    b.Property<string>("Condicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("DadoSimplesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SalaId");

                    b.HasDiscriminator().HasValue("DadoSimples");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorVariavel", b =>
                {
                    b.HasOne("Dicenamics.Models.DadoSimples", "Dado")
                        .WithMany()
                        .HasForeignKey("DadoFaces");

                    b.Navigation("Dado");
                });

            modelBuilder.Entity("Dicenamics.Models.Sala", b =>
                {
                    b.HasOne("Dicenamics.Models.Usuario", "UsuarioMestre")
                        .WithMany()
                        .HasForeignKey("UsuarioMestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMestre");
                });

            modelBuilder.Entity("Dicenamics.Models.Usuario", b =>
                {
                    b.HasOne("Dicenamics.Models.Sala", null)
                        .WithMany("Convidados")
                        .HasForeignKey("SalaId");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoSimples", b =>
                {
                    b.HasOne("Dicenamics.Models.Sala", null)
                        .WithMany("DadosCriados")
                        .HasForeignKey("SalaId");
                });

            modelBuilder.Entity("Dicenamics.Models.Sala", b =>
                {
                    b.Navigation("Convidados");

                    b.Navigation("DadosCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
