// <auto-generated />
using Dicenamics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dicenamics.Migrations
{
    [DbContext(typeof(AppDatabase))]
    partial class AppDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("Dicenamics.Models.DadoSimples", b =>
                {
                    b.Property<int>("DadoSimplesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoSimplesId");

                    b.ToTable("DadosSimples");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorFixo", b =>
                {
                    b.Property<int>("ModificadorFixoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModificadorFixoId");

                    b.ToTable("ModificadoresFixos");
                });
#pragma warning restore 612, 618
        }
    }
}
