// <auto-generated />
using System;
using Dicenamics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dicenamics.Migrations
{
    [DbContext(typeof(AppDatabase))]
    partial class AppDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("Dicenamics.Models.AcessoSalaDados", b =>
                {
                    b.Property<int>("AcessoSalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcessoSalaId");

                    b.HasIndex("SalaId");

                    b.ToTable("AcessosSalasDados");
                });

            modelBuilder.Entity("Dicenamics.Models.AcessoUsuarioDados", b =>
                {
                    b.Property<int>("AcessoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcessoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AcessosUsuariosDados");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoComposto", b =>
                {
                    b.Property<int>("DadoCompostoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcessoUsuarioDadosAcessoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DadoCompostoId");

                    b.HasIndex("AcessoUsuarioDadosAcessoUsuarioId");

                    b.ToTable("DadosCompostos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DadoComposto");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoSimples", b =>
                {
                    b.Property<int>("DadoSimplesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcessoUsuarioDadosAcessoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Faces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("DadoSimplesId");

                    b.HasIndex("AcessoUsuarioDadosAcessoUsuarioId");

                    b.ToTable("DadosSimples");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DadoSimples");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorFixo", b =>
                {
                    b.Property<int>("ModificadorFixoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModificadorFixoId");

                    b.ToTable("ModificadoresFixos");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorVariavel", b =>
                {
                    b.Property<int>("ModificadorVariavelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoSimplesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ModificadorVariavelId");

                    b.HasIndex("DadoSimplesId");

                    b.ToTable("ModificadoresVariaveis");
                });

            modelBuilder.Entity("Dicenamics.Models.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSimples")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioMestreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalaId");

                    b.HasIndex("UsuarioMestreId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Dicenamics.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.HasIndex("SalaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoCompostoSala", b =>
                {
                    b.HasBaseType("Dicenamics.Models.DadoComposto");

                    b.Property<int?>("AcessoSalaDadosAcessoSalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoCompostoSalaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AcessoSalaDadosAcessoSalaId");

                    b.HasDiscriminator().HasValue("DadoCompostoSala");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoSimplesSala", b =>
                {
                    b.HasBaseType("Dicenamics.Models.DadoSimples");

                    b.Property<int?>("AcessoSalaDadosAcessoSalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoSimplesSalaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AcessoSalaDadosAcessoSalaId");

                    b.HasDiscriminator().HasValue("DadoSimplesSala");
                });

            modelBuilder.Entity("Dicenamics.Models.AcessoSalaDados", b =>
                {
                    b.HasOne("Dicenamics.Models.Sala", "Sala")
                        .WithMany("DadosCriados")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Dicenamics.Models.AcessoUsuarioDados", b =>
                {
                    b.HasOne("Dicenamics.Models.Usuario", "Usuario")
                        .WithMany("DadosPessoais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoComposto", b =>
                {
                    b.HasOne("Dicenamics.Models.AcessoUsuarioDados", null)
                        .WithMany("DadosCompostos")
                        .HasForeignKey("AcessoUsuarioDadosAcessoUsuarioId");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoSimples", b =>
                {
                    b.HasOne("Dicenamics.Models.AcessoUsuarioDados", null)
                        .WithMany("DadosSimples")
                        .HasForeignKey("AcessoUsuarioDadosAcessoUsuarioId");
                });

            modelBuilder.Entity("Dicenamics.Models.ModificadorVariavel", b =>
                {
                    b.HasOne("Dicenamics.Models.DadoSimples", "Dado")
                        .WithMany()
                        .HasForeignKey("DadoSimplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dado");
                });

            modelBuilder.Entity("Dicenamics.Models.Sala", b =>
                {
                    b.HasOne("Dicenamics.Models.Usuario", "UsuarioMestre")
                        .WithMany()
                        .HasForeignKey("UsuarioMestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMestre");
                });

            modelBuilder.Entity("Dicenamics.Models.Usuario", b =>
                {
                    b.HasOne("Dicenamics.Models.Sala", null)
                        .WithMany("Convidados")
                        .HasForeignKey("SalaId");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoCompostoSala", b =>
                {
                    b.HasOne("Dicenamics.Models.AcessoSalaDados", null)
                        .WithMany("DadosCompostosSala")
                        .HasForeignKey("AcessoSalaDadosAcessoSalaId");
                });

            modelBuilder.Entity("Dicenamics.Models.DadoSimplesSala", b =>
                {
                    b.HasOne("Dicenamics.Models.AcessoSalaDados", null)
                        .WithMany("DadosSimplesSala")
                        .HasForeignKey("AcessoSalaDadosAcessoSalaId");
                });

            modelBuilder.Entity("Dicenamics.Models.AcessoSalaDados", b =>
                {
                    b.Navigation("DadosCompostosSala");

                    b.Navigation("DadosSimplesSala");
                });

            modelBuilder.Entity("Dicenamics.Models.AcessoUsuarioDados", b =>
                {
                    b.Navigation("DadosCompostos");

                    b.Navigation("DadosSimples");
                });

            modelBuilder.Entity("Dicenamics.Models.Sala", b =>
                {
                    b.Navigation("Convidados");

                    b.Navigation("DadosCriados");
                });

            modelBuilder.Entity("Dicenamics.Models.Usuario", b =>
                {
                    b.Navigation("DadosPessoais");
                });
#pragma warning restore 612, 618
        }
    }
}
