### Criar um dado simples
POST https://localhost:7151/dicenamics/dados/base/criar
Content-Type: application/json

{
    "Nome" : "3D6 Padrão",
    "Faces" : 6,
    "Quantidade" : 3,
    "Condicao" : ""
}

### Buscar por Id
GET https://localhost:7151/dicenamics/dados/base/buscar/1

### Listar dados simples
GET https://localhost:7151/dicenamics/dados/base/listar

### Atualizar dado simples por id
PUT https://localhost:7151/dicenamics/dados/base/atualizar/1
Content-Type: application/json

{
    "Nome" : "10D6 Padrão",
    "Faces" : 6,
    "Quantidade" : 10,
    "Condicao" : "ved3"
}

### Remover dado simples
DELETE https://localhost:7151/dicenamics/dados/base/deletar/1

### Rolar um dado simples
https://localhost:7151/dicenamics/dados/base/rolar/1