### Criar um modificador
POST https://localhost:7151/modificador/criar
Content-Type: application/json

{
    "Nome" : "Corte",
    "Valor" : 15
}

### Buscar por Id
GET https://localhost:7151/modificador/buscar/1

### Listar modificadores
GET https://localhost:7151/dicenamics/modificador/listar

### Atualizar modificador por id
PUT https://localhost:7151/dicenamics/modificador/atualizar/1
Content-Type: application/json

{
    "Nome" : "Fogo",
    "Valor" : 3
}

### Remover modificador
DELETE https://localhost:7151/dicenamics/modificador/deletar/2